addons:
  apt:
    packages:
      - sshpass

matrix:
  include:
    - language: node_js
      if: branch IN (master)
      sudo: required
      node_js:
        - "lts/*"
      cache: yarn
      services:
        - docker
      before_install:
        - cd frontend
      script:
        - yarn build
        - docker build -t frontend .
        - docker save frontend > frontend.tar
      after_success:
        - export SSHPASS=$DEPLOY_PASS
        - sshpass -e scp -P $DEPLOY_PORT -o StrictHostKeyChecking=no $TRAVIS_BUILD_DIR/frontend/frontend.tar $DEPLOY_USER@$DEPLOY_HOST:~/app/frontend.tar
        - sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST -p $DEPLOY_PORT 'docker load -i ~/app/frontend.tar'

    - language: docker-compose
      if: branch IN (master)
      sudo: false
      script:
        - export SSHPASS=$DEPLOY_PASS
        - sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST -p $DEPLOY_PORT 'cd ~/source/AdaptationProject && git checkout master && git pull && docker-compose restart'
