addons:
  apt:
    packages:
      - sshpass

services:
  - docker

sudo: required

language: generic

if: branch = master OR env(ADAPT_BUILD_MODE) = test

before_install:
  - test "$ADAPT_BUILD_MODE" = test || export ADAPT_BUILD_MODE=prod
  - test "$ADAPT_BUILD_MODE" = prod || export ADAPT_EMAIL1=$ADAPT_TEST_EMAIL1
  - test "$ADAPT_BUILD_MODE" = prod || export ADAPT_EMAIL2=$ADAPT_TEST_EMAIL2
  - test "$ADAPT_BUILD_MODE" = prod || export ADAPT_SMTP_HOST=$ADAPT_TEST_SMTP_HOST
  - test "$ADAPT_BUILD_MODE" = prod || export ADAPT_SMTP_USER=$ADAPT_TEST_SMTP_USER
  - test "$ADAPT_BUILD_MODE" = prod || export ADAPT_SMTP_PASSWORD=$ADAPT_TEST_SMTP_PASSWORD
  - test "$ADAPT_BUILD_MODE" = prod || echo ADAPT_MOCK_EMAIL=$ADAPT_MOCK_EMAIL >> .env
  - export SSHPASS=$DEPLOY_PASS
  - export SSH_CMD="sshpass -e ssh -p $DEPLOY_PORT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

install:
  - docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.$ADAPT_BUILD_MODE.yml build

after_success:
  - docker save adapt-backend adapt-frontend | $SSH_CMD $DEPLOY_USER@$DEPLOY_HOST docker load
  - rsync -e "$SSH_CMD" docker-compose.yml $DEPLOY_USER@$DEPLOY_HOST:~/adapt-$ADAPT_BUILD_MODE/
  - rsync -e "$SSH_CMD" docker-compose.$ADAPT_BUILD_MODE.yml $DEPLOY_USER@$DEPLOY_HOST:~/adapt-$ADAPT_BUILD_MODE/docker-compose.override.yml
  - rsync -e "$SSH_CMD" .env $DEPLOY_USER@$DEPLOY_HOST:~/adapt-$ADAPT_BUILD_MODE/
  - test "$ADAPT_BUILD_MODE" = prod || rsync -e "$SSH_CMD" --chmod=+x copy-db.sh $DEPLOY_USER@$DEPLOY_HOST:~/adapt-test/db-scripts/
  - $SSH_CMD $DEPLOY_USER@$DEPLOY_HOST "cd adapt-$ADAPT_BUILD_MODE && docker-compose down && docker-compose up -d"
