version: "2.1"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
    networks:
      - frontend

  postgres:
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres
      postgres:
        aliases:
          - postgres-prod

  backend:
    image: adapt-backend:prod

  frontend:
    image: adapt-frontend:prod
    networks:
      default:
        aliases:
          - frontend
      frontend:
        aliases:
          - frontend-prod

networks:
  postgres:
    name: adapt-postgres
  frontend:
    name: adapt-frontend
