version: "2.1"

services:
  postgres:
    ports:
      - 5433:5432
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d/
    networks:
      default:
        aliases:
          - postgres
      postgres:
        aliases:
          - postgres-test

  backend:
    image: adapt-backend:test

  frontend:
    image: adapt-frontend:test
    networks:
      default:
        aliases:
          - frontend
      frontend:
        aliases:
          - frontend-test

networks:
  postgres:
    external:
      name: adapt-postgres
  frontend:
    external:
      name: adapt-frontend
